### ISSUE TITLE
Setup Travis for statist7 account

### ISSUE THREAD

**Issue by tamuri** [statist7/LMSgrowth2#47]
@statist7 - we need to setup Travis to continue to test builds of LMSgrowth2. It's simply a matter of logging into Travis using your Github credentials and adding LMSgrowth2 as a repository you want to use with Travis. Instructions are [here](https://docs.travis-ci.com/user/tutorial/) - you only have to setup Travis+Github repo because we already have travis.yml in this repo.

**Comment by statist7** [comment]
I've signed up to Travis, and am closing the issue.
